<?php

namespace App\Console\Commands;

use App\lichhen;
use App\Mail\ThongBaoLichHenChoNhanVien;
use App\trangthai_lichhen;
use Illuminate\Console\Command;
use Illuminate\Support\Carbon;

class CronCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'cron:run {now?}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    public function arguments()
    {
        return parent::arguments(); // TODO: Change the autogenerated stub
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $hour = 20;
        $minute = 38;
        $saveTo = public_path('settings.json');

//        $customTime = $this->argument('now');
//        if($customTime) {
//            $customTime = explode(":", $customTime);
//            $hour = $customTime[0];
//            $minute = $customTime[1];
//        }
//        $this->line("Send Email at {$hour}:$minute every day.");

        $trangthailichhens = trangthai_lichhen::query()->get()->pluck('id', 'ten');
        while(true) {
            $now = Carbon::now();
            $settings = json_decode(file_get_contents($saveTo));
            $customTime = data_get($settings, 'send_mail_every_day', '');
            $customTime = explode(":", $customTime);
            $hour = $customTime[0];
            $minute = $customTime[1];
            if($now->hour == $hour && $now->minute == $minute) {


                $this->line($now->toString() . "| " . $now->hour);
                $tomorrow = $now->addDay(1);

                $lichhens = lichhen::query()->whereDate('thoigian', $tomorrow)
                    ->where('trangthai_id', '=', $trangthailichhens['Chờ phỏng vấn'])
                    ->get();
                $this->line($lichhens->count());

                foreach ($lichhens as $lichhen) {
                    $nhanviens = $lichhen->nhanviens;
                    foreach ($nhanviens as $nhanvien) {
                        \Mail::to($nhanvien)->send(new ThongBaoLichHenChoNhanVien($lichhen));
                    }
                }
                $this->line('done');
            }

            sleep(60);
        }
    }
}
