<?php

use Illuminate\Database\Seeder;

class HososTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(Faker\Generator $faker)
    {
        $vaitro_ungvien_id = \App\vaitro::query()->where('ten', '=','Ứng viên')->first()->id;
        $ungviens = \App\User::query()->where("vaitro_id", $vaitro_ungvien_id)->pluck('id');
        $trangthai_hosos = \App\trangthai_hoso::query()->get()->pluck('id','ten');
        $thanhphos=\App\Tinh\Thanhpho::query()->get()->pluck('id','ten');
        $tintuyendungs=\App\tintuyendung::query()->get()->pluck('id','tieude');
        \App\hoso::query()->create([
            'cv'=>'Pham-Nguyen-Thanh-TopCV.vn-260620.01724.pdf',
            'ten'=>'Phạm Nguyên Thành',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'phamnguyenthanh-hn@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Đã trở thành nhân viên'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Kỹ sư hệ thống CNTT (DBA)'],
            'created_at' => $faker->dateTimeBetween('-6 months', 'now'),
        ]);

        \App\hoso::query()->create([
            'cv'=>'Dinh-Nhat-Minh-TopCV.vn-260620.01956.pdf',
            'ten'=>'Đinh Nhật Minh',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'dinhnhatminh92@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Đã trở thành nhân viên'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Kỹ sư hệ thống CNTT (DBA)'],
            'created_at' => $faker->dateTimeBetween('-6 months', 'now'),
        ]);
        \App\hoso::query()->create([
            'cv'=>'Vu-Kim-Ngoc-TopCV.vn-260620.02239.pdf',
            'ten'=>'Vũ Kim Ngọc',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'vukimngoc2309@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Đã trở thành nhân viên'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Kỹ sư hệ thống CNTT (DBA)'],
            'created_at' => $faker->dateTimeBetween('-6 months', 'now'),
        ]);
        \App\hoso::query()->create([
            'cv'=>'Tran-Hai-Nam-TopCV.vn-260620.02436.pdf',
            'ten'=>'Trần Hải Nam',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'tranhainam0907@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Đã trở thành nhân viên'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Kỹ sư an ninh mạng'],
            'created_at' => $faker->dateTimeBetween('-6 months', 'now'),
        ]);
        \App\hoso::query()->create([
            'cv'=>'Vu-Nam-Anh-TopCV.vn-260620.02623.pdf',
            'ten'=>'Vũ Nam Anh',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'namanh0790@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Đã trở thành nhân viên'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Kỹ sư an ninh mạng'],
            'created_at' => $faker->dateTimeBetween('-6 months', 'now'),
        ]);
        \App\hoso::query()->create([
            'cv'=>'Tran-Quoc-Hai-TopCV.vn-260620.02820.pdf',
            'ten'=>'Trần Quốc Hải',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'haitranquoc-qn@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Đã trở thành nhân viên'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Kỹ sư an ninh mạng'],
            'created_at' => $faker->dateTimeBetween('-6 months', 'now'),
        ]);
        \App\hoso::query()->create([
            'cv'=>'Vu-Minh-Tri-TopCV.vn-260620.22633.pdf',
            'ten'=>'Vũ Minh Trí',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'minhtri080799@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Phỏng vấn thất bại'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Kỹ sư an ninh mạng'],
            'created_at' => $faker->dateTimeBetween('-6 months', 'now'),
        ]);
        \App\hoso::query()->create([
            'cv'=>'Do-Minh-Gia-Vu-TopCV.vn-260620.22830.pdf',
            'ten'=>'Đỗ Minh Gia Vũ',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'dominhgiavu0708@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Phỏng vấn thất bại'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Phân tích yêu cầu chính'],
            'created_at' => $faker->dateTimeBetween('-6 months', 'now'),
        ]);
        \App\hoso::query()->create([
            'cv'=>'Tran-Minh-Thu-TopCV.vn-260620.23037.pdf',
            'ten'=>'Trần Minh Thu',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'tranminhthu0712@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Đã trở thành nhân viên'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Phân tích yêu cầu chính'],
            'created_at' => $faker->dateTimeBetween('-6 months', 'now'),
        ]);
        \App\hoso::query()->create([
            'cv'=>'Le-Nguyen-Hai-Nam-TopCV.vn-260620.23249.pdf',
            'ten'=>'Lê Nguyên Hải Nam',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'hainam.bn.0708@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Đã trở thành nhân viên'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Phân tích yêu cầu chính'],
            'created_at' => $faker->dateTimeBetween('-6 months', 'now'),
        ]);
        \App\hoso::query()->create([
            'cv'=>'Tran-Minh-An-TopCV.vn-260620.23514.pdf',
            'ten'=>'Trần Minh An',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'anminhtran90@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Đã trở thành nhân viên'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Chuyên viên phân tích kinh doanh trực tuyến'],
            'created_at' => $faker->dateTimeBetween('-6 months', 'now'),
        ]);
        \App\hoso::query()->create([
            'cv'=>'Vu-Ngoc-Long-TopCV.vn-260620.23702.pdf',
            'ten'=>'Vũ Ngọc Long',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'ngoclong.tn60@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Phỏng vấn thất bại'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Nhà phân tích nghiên cứu'],
            'created_at' => $faker->dateTimeBetween('-6 months', 'now'),
        ]);
        \App\hoso::query()->create([
            'cv'=>'Thai-Hong-Anh-TopCV.vn-260620.23915.pdf',
            'ten'=>'Thái Hồng Anh',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'honganhthai-tn@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Từ chối tham gia phỏng vấn'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Nhà phân tích nghiên cứu'],
            'created_at' => $faker->dateTimeBetween('-6 months', 'now'),
        ]);
        \App\hoso::query()->create([
            'cv'=>'Le-Thu-An-TopCV.vn-260620.24116.pdf',
            'ten'=>'Lê Thu An',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'thuan090998-hnn@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Từ chối tham gia phỏng vấn'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Nhà phân tích nghiên cứu'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Pham-Van-Anh-TopCV.vn-260620.24302.pdf',
            'ten'=>'Phạm Vân Anh',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'vananh.070896@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Từ chối tham gia phỏng vấn'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Quản lý phương tiện truyền thông xã hội'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Pham-Quoc-Anh-TopCV.vn-260620.24515.pdf',
            'ten'=>'Phạm Quốc Anh',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'anhquoc.vn.95@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Đã trở thành nhân viên'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Quản lý phương tiện truyền thông xã hội'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Le-Phu-Binh-TopCV.vn-260620.24731.pdf',
            'ten'=>'Lê Phú Bình',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'binhle0709-bg@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Đã trở thành nhân viên'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Truyền thông chiến lược, Quan hệ công'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Le-Quoc-Bao-TopCV.vn-260620.24949.pdf',
            'ten'=>'Lê Quốc Bảo',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'lequocbao.92@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Đã trở thành nhân viên'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Bảo trì vận hành cơ sở'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Vu-Thai-Son-TopCV.vn-260620.25127.pdf',
            'ten'=>'Vũ Thái Sơn',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'vuthaison.92@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Phỏng vấn thất bại'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Tuyển kỹ sư có kinh nghiệm'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Do-Ha-Ngan-TopCV.vn-260620.25307.pdf',
            'ten'=>'Đỗ Hà Ngân',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'nganha0708@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Đã trở thành nhân viên'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Hỗ trợ tiếp thị sản phẩm'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Do-Cong-Minh-TopCV.vn-260620.30033.pdf',
            'ten'=>'Đỗ Công Minh',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'congminh0704@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Phỏng vấn thất bại'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Tuyển kỹ sư có kinh nghiệm'],
        ]);
        for($i = 1; $i <= 8; $i++) {
        \App\hoso::query()->create([
            'ten'=>$faker->name,
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>$faker->email,
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Bị từ chối CV'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$faker->randomElement($tintuyendungs),
        ]);}



        \App\hoso::query()->create([
            'cv'=>'Pham-Thanh-Xuan-TopCV.vn-260620.30241.pdf',
            'ten'=>'Phạm Thanh Xuân',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'phamthanhxuan.98@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Đã trở thành nhân viên'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Thiết kế sản phẩm'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Dinh-Xuan-Thanh-TopCV.vn-260620.30452.pdf',
            'ten'=>'Đinh Xuân Thành',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'dinhthanh.th@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Đã trở thành nhân viên'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Nhân viên bán hàng'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Tran-Ngoc-Vu-TopCV.vn-260620.30616.pdf',
            'ten'=>'Trần Ngọc Vũ',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'tranngocvu.bg@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Phỏng vấn thất bại'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Tiếp thị sản phẩm phần mềm'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Do-Anh-Vu-TopCV.vn-260620.30816.pdf',
            'ten'=>'Đỗ Anh Vũ',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'doanhvu.dl@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Phỏng vấn thất bại'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Tiếp thị sản phẩm phần mềm'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Vu-Thai-Hoang-TopCV.vn-260620.31006.pdf',
            'ten'=>'Vũ Thái Hoàng',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'vuthaihoang.kn@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Đã trở thành nhân viên'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Tiếp thị sản phẩm phần mềm'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Vu-Ngoc-Tinh-TopCV.vn-260620.31149.pdf',
            'ten'=>'Vũ Ngọc Tình',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'vungoctinh.kn@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Đã trở thành nhân viên'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Tiếp thị sản phẩm phần mềm'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Dinh-Thai-Tuan-TopCV.vn-260620.31412.pdf',
            'ten'=>'Đinh Thái Tuấn',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'dinhthaituan.kg@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Đã trở thành nhân viên'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Tiếp thị sản phẩm phần mềm'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Pham-Hong-Ha-TopCV.vn-260620.31549.pdf',
            'ten'=>'Phạm Hồng Hà',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'hongha.dn@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Phỏng vấn thất bại'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Quản lý tổ chức, học tập và phát triển'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Pham-Hong-Linh-TopCV.vn-260620.31746.pdf',
            'ten'=>'Phạm Hồng Linh',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'honglinh.td@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Phỏng vấn thất bại'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Kế hoạch nhân sự'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Nguyen-Viet-Tung-TopCV.vn-260620.32039.pdf',
            'ten'=>'Nguyễn Viết Tùng',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'nguyenviettung.gl@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Phỏng vấn thất bại'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Quản lý kế hoạch sản phẩm'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Dang-Viet-Hoang-TopCV.vn-260620.32331.pdf',
            'ten'=>'Đặng Việt Hoàng',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'viethoang.bd@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Không tham gia phỏng vấn'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Quản lý kế hoạch sản phẩm'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Hoang-Luu-Ly-TopCV.vn-260620.32602.pdf',
            'ten'=>'Hoàng Lưu Ly',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'luudely.vn@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Không tham gia phỏng vấn'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Quản lý bán hàng'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Hoang-Quoc-Vinh-TopCV.vn-260620.32823.pdf',
            'ten'=>'Hoàng Quốc Vinh',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'quocvinh.vn@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Không tham gia phỏng vấn'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Quản lý bán hàng'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Dinh-Khanh-Ngoc-TopCV.vn-260620.33049.pdf',
            'ten'=>'Đinh Khánh Ngọc',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'dinhkhanhngoc.vn@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Đặt lịch thành công'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Quản lý kế hoạch dự án chiến lược'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Pham-Thu-Hong-TopCV.vn-260620.33332.pdf',
            'ten'=>'Phạm Thu Hồng',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'phamthuhong.vn@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Đặt lịch thành công'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Quản lý kế hoạch dự án chiến lược'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Ho-Quoc-Dat-TopCV.vn-260620.33718.pdf',
            'ten'=>'Hồ Quốc Đạt',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'hoquocdat.vn@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Đặt lịch thành công'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Giám đốc, Kế hoạch và Chiến lược hoạt động'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Nguyen-Hoang-Yen-TopCV.vn-260620.35031.pdf',
            'ten'=>'Nguyễn Hoàng Yến',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'hoangyen.qg@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Đặt lịch thành công'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Giám đốc, Kế hoạch và Chiến lược hoạt động'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Pham-Nguyen-Hung-TopCV.vn-260620.35243.pdf',
            'ten'=>'Phạm Nguyên Hùng',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'phamnguyenhung.qg@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Đặt lịch thành công'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Giám đốc, Kế hoạch và Chiến lược hoạt động'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Thai-Nam-Anh-TopCV.vn-260620.35445.pdf',
            'ten'=>'Thái Nam Anh',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'thaianh.qg@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Đặt lịch thành công'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Giám đốc, Kế hoạch và Chiến lược hoạt động'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Van-Tien-Hai-TopCV.vn-260620.35714.pdf',
            'ten'=>'Văn Tiến Hải',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'tienhai.qg@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Đặt lịch thành công'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Giám đốc, Kế hoạch và Chiến lược hoạt động'],
        ]);




        \App\hoso::query()->create([
            'cv'=>'Nguyen-Dinh-Quoc-TopCV.vn-260620.40116.pdf',
            'ten'=>'Nguyễn Đình Quốc',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'dinhquochn@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Chờ phê duyệt CV'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Kỹ sư xác nhận thiết kế (hợp đồng)'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Nguyen-Van-Dong-TopCV.vn-260620.40320.pdf',
            'ten'=>'Nguyễn Văn Đông',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'dongvan.dv@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Chờ phê duyệt CV'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Kỹ sư xác nhận thiết kế (hợp đồng)'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Nguyen-Hoang-Tuan-Duong-TopCV.vn-260620.40559.pdf',
            'ten'=>'Nguyễn Hoàng Tuấn Dương',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'tuanduonghtd@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Chờ phê duyệt CV'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Kỹ sư hợp đồng - Tích hợp thiết kế'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Nguyen-Ngoc-Anh-TopCV.vn-260620.40804.pdf',
            'ten'=>'Nguyễn Ngọc Ánh',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'ngocanh.hn@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Chờ phê duyệt CV'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Điều hành đám mây (Hợp đồng 8 tháng)'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Nguyen-Trong-Truong-TopCV.vn-260620.41020.pdf',
            'ten'=>'Nguyễn Trọng Trường',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'nguyentrongtruong@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Chờ phê duyệt CV'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Quản lý chương trình cao cấp (Mạng) Hợp đồng 12 tháng'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Ly-Chien-Thang-TopCV.vn-260620.41234.pdf',
            'ten'=>'Lý Chiến Thắng',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'chienthang-tn@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Được chấp nhận CV'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Kỹ sư hệ thống CNTT (DBA)'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Quan-Thanh-Quan-TopCV.vn-260620.41503.pdf',
            'ten'=>'Quán Thanh Quân',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'quanquan.vn@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Được chấp nhận CV'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Kỹ sư hệ thống CNTT (DBA)'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Luu-Thanh-Chien-TopCV.vn-260620.42047.pdf',
            'ten'=>'Lưu Thanh Chiến',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'luuthanhchien.vn@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Được chấp nhận CV'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Kỹ sư an ninh mạng'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Nguyen-Anh-Tu-TopCV.vn-260620.42302.pdf',
            'ten'=>'Nguyễn Anh Tú',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'anhtu-anhtu.vn@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Chờ tiếp tục phỏng vấn'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Tiếp thị sản phẩm phần mềm'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Do-Duc-Quang-TopCV.vn-260620.42500.pdf',
            'ten'=>'Đỗ Đức Quang',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'quangducdo.vn@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Chờ tiếp tục phỏng vấn'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Tiếp thị sản phẩm phần mềm'],
        ]);
        \App\hoso::query()->create([
            'cv'=>'Vo-Anh-Hao-TopCV.vn-260620.42747.pdf',
            'ten'=>'Võ Anh Hào',
            'socmt'=>$faker->numberBetween(100000000,999999999999),
            'ngaycapcmt'=>$faker->date($format='2013-02-24',$max='2019-03-26'),
            'noicapcmt_id'=>$faker->randomElement($thanhphos),
            'ngaysinh'=>'1998-02-28',
            'gioitinh'=>'1',
            'ngaycothebatdaulamviec'=>'2020-10-08',
            'sodienthoai'=>$faker->numberBetween(1000000000,9999999999),
            'email'=>'voanhhao.vn@gmail.com',
            'quanhuyen'=>$faker->city,
            'diachichitiet'=>$faker->address,
            'hocvan'=>$faker->randomElement(['Đại học','Cao đẳng','Tốt nghiệp cấp 3','Thạc sĩ']),
            'kinhnghiemlamviec'=>$faker->randomElement(['Đã có kinh nghiệm 1 năm','Đã có kinh nghiệm 2 năm','Đã có kinh nghiệm 3 năm','Đã có kinh nghiệm 4 năm','Đã có kinh nghiệm 5 năm']),
            'ngonngu'=>$faker->randomElement(['Anh','Hàn Quốc','Đức','Pháp','Nhật']),
            'cacgiaychungnhan_chungchi'=>$faker->randomElement(['Auto card','TOEIC','IELTS','MBA','CFMO']),
            'ungvien_id'=>$faker->randomElement($ungviens),
            'trangthai_hoso_id'=>$trangthai_hosos['Chờ tiếp tục phỏng vấn'],
            'thanhpho_id'=>$faker->randomElement($thanhphos),
            'tintuyendung_id'=>$tintuyendungs['Nhân viên bán hàng'],
        ]);


    }
}
